"""T011 / US1 / SC-002 / SC-003: diary format resolution and structure extraction
behave exactly as documented, with zero silent picks on numeric-date ambiguity.

Ties ``tests/helpers/diary_reference.py``'s ``extract_structure`` /
``resolve_date_ambiguity`` / ``resolve_format`` / ``apply_format`` (T006/T007/T009) to
``tests/fixtures/diary/golden-structures.json`` and
``tests/fixtures/diary/resolution-matrix.json`` (T010) and to
``skills/diary/references/format.md`` (data-model.md §3, §3.1, §4, §5, §6, §8, §9).

Everything here is parametrized off the two fixtures — no hand-written expected
``Structure``/notice/source values live in this module. Both fixtures were generated by
running the reference encoding and then hand-audited against data-model.md (T010's own
job); this module only re-asserts on the artifacts, never on prose (Constitution VIII).

House style follows ``tests/contract/test_catalog_resolution.py``: a non-vanishing guard
on each fixture's case-id/key set first, then full parametrization over every case.
"""

import inspect
import re

import pytest

from conftest import REPO_ROOT, fixture_path, load_fixture
from helpers.diary_reference import (
    FORMAT_INPUT_KEYS,
    MINIMAL_DEFAULT,
    apply_format,
    extract_structure,
    resolve_date_ambiguity,
    resolve_format,
)

MATRIX = load_fixture("diary", "resolution-matrix.json")
CASES = MATRIX["cases"]
CASES_BY_ID = {case["id"]: case for case in CASES}

GOLDEN = load_fixture("diary", "golden-structures.json")


def _entries(fixture_name):
    return load_fixture("diary", "{}.json".format(fixture_name))["entries"]


# ---------------------------------------------------------------------------
# Non-vanishing guards, first (test_catalog_resolution.py's TA5-style
# precedent) — a truncated or renamed fixture must fail here, not silently
# shrink a parametrize below to a smaller, still-green set.
# ---------------------------------------------------------------------------

EXPECTED_CASE_IDS = frozenset(
    {
        "template-absent-entries-consistent",
        "template-absent-entries-bold",
        "template-absent-entries-inconsistent",
        "template-absent-entries-ambiguous-date",
        "template-absent-entries-disambiguating",
        "template-absent-entries-short",
        "template-absent-entries-empty",
        "template-well-formed",
        "template-malformed-number",
        "template-malformed-object",
        "template-malformed-empty-string",
        "template-malformed-whitespace-only",
    }
)

EXPECTED_GOLDEN_KEYS = frozenset(
    {
        "entries-consistent",
        "entries-bold",
        "entries-inconsistent",
        "entries-ambiguous-date",
        "entries-disambiguating",
        "entries-short",
        "entries-labeled-causal",
        "MINIMAL_DEFAULT",
    }
)


def test_matrix_case_ids_are_exactly_the_documented_set():
    case_ids = set(CASES_BY_ID)
    assert case_ids == EXPECTED_CASE_IDS, (
        "resolution-matrix.json's case-id set must equal the documented set exactly — "
        "a renamed or dropped id must fail here rather than silently disappearing from "
        "the parametrize below; missing=%r extra=%r"
        % (sorted(EXPECTED_CASE_IDS - case_ids), sorted(case_ids - EXPECTED_CASE_IDS))
    )


def test_golden_structures_cover_every_entry_fixture_set_and_the_default():
    assert set(GOLDEN) == EXPECTED_GOLDEN_KEYS, (
        "golden-structures.json must carry exactly one list per entries-*.json fixture "
        "plus MINIMAL_DEFAULT; missing=%r extra=%r"
        % (
            sorted(EXPECTED_GOLDEN_KEYS - set(GOLDEN)),
            sorted(set(GOLDEN) - EXPECTED_GOLDEN_KEYS),
        )
    )


def test_golden_minimal_default_matches_the_encoding_constant():
    # golden-structures.json's MINIMAL_DEFAULT entry must be the same value as the
    # module's own hand-written constant (data-model.md §6), not merely a plausible
    # look-alike copied in by hand — this is what makes it safe to reuse below instead
    # of a fixture-local re-typing of the same seven sections.
    assert GOLDEN["MINIMAL_DEFAULT"] == MINIMAL_DEFAULT


# ---------------------------------------------------------------------------
# The resolution matrix (SC-002) — source, the exact notice SET, and the
# resolved structure, per case.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("case", CASES, ids=[case["id"] for case in CASES])
def test_matrix_case_resolves_exactly_as_expected(case):
    entries = _entries(case["entries_fixture"])
    resolution = resolve_format(case["template"], entries)
    expected = case["expected"]

    assert resolution["source"] == expected["source"], (
        "%s: source must be %r — %s; got %r"
        % (case["id"], expected["source"], case["why"], resolution["source"])
    )
    # Notices compared as a SET and exactly — never "contains" — so a spurious extra
    # notice (or a missing one) fails here.
    actual_notice_kinds = set(notice["kind"] for notice in resolution["notices"])
    assert actual_notice_kinds == set(expected["notices"]), (
        "%s: notice kind set must equal %r exactly — %s; got %r"
        % (case["id"], sorted(expected["notices"]), case["why"], sorted(actual_notice_kinds))
    )
    assert resolution["structure"] == expected["resolved"], (
        "%s: resolved structure must equal the fixture's expectation field-for-field — "
        "%s" % (case["id"], case["why"])
    )


# ---------------------------------------------------------------------------
# Extraction goldens (SC-003) — per entry, field-for-field.
# ---------------------------------------------------------------------------

_GOLDEN_ENTRY_CASES = []
for _fixture_name, _structures in GOLDEN.items():
    if _fixture_name == "MINIMAL_DEFAULT":
        continue
    _entries_list = _entries(_fixture_name)
    assert len(_entries_list) == len(_structures), (
        "%s: golden-structures.json must carry exactly one Structure per entry"
        % _fixture_name
    )
    for _index, (_entry, _expected) in enumerate(zip(_entries_list, _structures)):
        _GOLDEN_ENTRY_CASES.append((_fixture_name, _index, _entry["content"], _expected))

_GOLDEN_ENTRY_IDS = ["{}[{}]".format(name, index) for name, index, _, _ in _GOLDEN_ENTRY_CASES]


@pytest.mark.parametrize(
    "fixture_name, index, content, expected", _GOLDEN_ENTRY_CASES, ids=_GOLDEN_ENTRY_IDS
)
def test_extraction_golden_matches_field_for_field(fixture_name, index, content, expected):
    assert extract_structure(content) == expected, (
        "%s entry %d: extract_structure(content) must equal the golden Structure "
        "field-for-field (SC-003)" % (fixture_name, index)
    )


# ---------------------------------------------------------------------------
# The template branch's no-read property (US1 AS-1) — a real trap, not a
# plain list, so any consumption at all (iteration, len, truth-test,
# indexing) fails loudly rather than silently.
# ---------------------------------------------------------------------------


class _RaisingEntries:
    """Stands in for ``entries`` on the template-configured path. Every way a
    caller might read it — iterate, measure, truth-test, index — raises, so
    a ``resolve_format`` that touches ``entries`` at all on this path fails
    the test instead of merely "happening" to work because a real list was
    never actually consumed."""

    def __iter__(self):
        raise AssertionError("entries must not be iterated when a template is configured")

    def __len__(self):
        raise AssertionError("entries must not be measured when a template is configured")

    def __bool__(self):
        raise AssertionError("entries must not be truth-tested when a template is configured")

    def __getitem__(self, item):
        raise AssertionError("entries must not be indexed when a template is configured")


def test_template_branch_never_reads_entries():
    resolution = resolve_format("a well-formed configured template", _RaisingEntries())
    assert resolution == {
        "source": "template",
        "structure": None,
        "template": "a well-formed configured template",
        "notices": [],
    }


# ---------------------------------------------------------------------------
# Freshest-wins on entries-inconsistent.json — both the resulting structure
# and the entries_inconsistent notice.
# ---------------------------------------------------------------------------


def test_freshest_wins_structure_and_notice_on_inconsistent_entries():
    entries = _entries("entries-inconsistent")
    resolution = resolve_format(None, entries)

    assert set(notice["kind"] for notice in resolution["notices"]) == {"entries_inconsistent"}
    # The newest entry (index 0 — read_recent is most-recent-first) is what freshest-wins
    # adopts; golden-structures.json's own per-entry extraction of that same entry is the
    # independent source for what that structure must be, so this is not a second
    # hand-written copy of the same expectation.
    assert resolution["structure"] == GOLDEN["entries-inconsistent"][0]
    assert resolution["structure"] == CASES_BY_ID["template-absent-entries-inconsistent"][
        "expected"
    ]["resolved"]


# ---------------------------------------------------------------------------
# date_ambiguous on entries-ambiguous-date.json; its ABSENCE on
# entries-disambiguating.json, plus the resolved order propagated to every
# entry of the pass (resolve_format only ever returns entries[0]'s
# structure, so the propagation claim needs resolve_date_ambiguity called
# directly over the whole pass to be observable at all).
# ---------------------------------------------------------------------------


def test_date_ambiguous_notice_on_every_component_ambiguous_entries():
    resolution = resolve_format(None, _entries("entries-ambiguous-date"))
    assert set(notice["kind"] for notice in resolution["notices"]) == {"date_ambiguous"}


def test_disambiguating_entries_carry_no_date_ambiguous_notice():
    resolution = resolve_format(None, _entries("entries-disambiguating"))
    assert "date_ambiguous" not in set(notice["kind"] for notice in resolution["notices"])


def test_disambiguating_resolved_order_propagates_to_every_entry_in_the_pass():
    # The single unambiguous entry (third-newest, data-model.md §3.1 step 2) fixes the
    # order for the WHOLE pass, not just the newest entry resolve_format happens to
    # return. The expected pattern comes from the matrix fixture's own recorded
    # resolution, not a value typed into this test.
    expected_date_format = CASES_BY_ID["template-absent-entries-disambiguating"]["expected"][
        "resolved"
    ]["date_format"]

    entries = _entries("entries-disambiguating")
    structures = [extract_structure(entry["content"]) for entry in entries]
    resolved = resolve_date_ambiguity(structures)

    assert len(resolved) == len(entries)
    for structure in resolved:
        assert structure["date_format"] == expected_date_format, (
            "every entry in the pass must carry the adopted order, not only the "
            "entry resolve_format happens to return"
        )


# ---------------------------------------------------------------------------
# Malformed-template rows — the fallback structure is the match-recent one,
# never the default.
# ---------------------------------------------------------------------------

_MALFORMED_CASE_IDS = [
    case_id for case_id in CASES_BY_ID if case_id.startswith("template-malformed-")
]


def test_matrix_carries_more_than_one_malformed_shape():
    # "not a string" has more than one JSON shape (a number, an object) — this guards
    # against the malformed rows collapsing onto a single accidentally-easy case.
    assert len(_MALFORMED_CASE_IDS) >= 4


@pytest.mark.parametrize("case_id", _MALFORMED_CASE_IDS)
def test_malformed_template_falls_back_to_match_recent_not_default(case_id):
    case = CASES_BY_ID[case_id]
    entries = _entries(case["entries_fixture"])
    resolution = resolve_format(case["template"], entries)

    assert resolution["source"] == "matched"
    assert "template_malformed" in set(notice["kind"] for notice in resolution["notices"])
    assert resolution["structure"] != MINIMAL_DEFAULT, (
        "%s: a malformed template must fall through to match-recent, never silently "
        "resolve to the empty-diary default" % case_id
    )
    assert resolution["structure"] == case["expected"]["resolved"]


# ---------------------------------------------------------------------------
# The minimal default plus template_candidate on entries-empty.json.
# ---------------------------------------------------------------------------


def test_empty_entries_resolves_to_the_minimal_default_constant():
    resolution = resolve_format(None, _entries("entries-empty"))
    assert resolution["source"] == "default"
    assert resolution["structure"] == MINIMAL_DEFAULT
    assert set(notice["kind"] for notice in resolution["notices"]) == {"template_candidate"}


# ---------------------------------------------------------------------------
# Label pass-through (FR-005) — every block of entries-labeled-causal.json's
# sections is byte-identical in apply_format's output, plus the
# no-content-dropped property for its unmatched-label ("Timeline") block.
# ---------------------------------------------------------------------------


def _recovered_blocks(output):
    """Splits apply_format's output back into (heading_line, block) pairs.

    apply_format emits each piece as ``heading_line + "\\n" + block + "\\n\\n"``
    (data-model.md §8); none of the blocks in entries-labeled-causal.json's own
    `sections` list contain a blank line, so splitting the joined output on "\\n\\n"
    recovers each piece verbatim and a plain `==` comparison — never a substring `in`
    check a mutated block could still pass — is enough to prove byte-identity.
    """
    pieces = [piece for piece in output.split("\n\n") if piece]
    return [piece.split("\n", 1) for piece in pieces]


def test_label_pass_through_is_byte_identical_for_every_block():
    fixture = load_fixture("diary", "entries-labeled-causal.json")
    structure = resolve_format(None, fixture["entries"])["structure"]
    output = apply_format(structure, fixture["sections"])

    recovered = _recovered_blocks(output)
    recovered_blocks = [block for _heading, block in recovered]

    assert len(recovered) == len(fixture["sections"]), (
        "no content is ever dropped (data-model.md §8) — every input section must "
        "produce exactly one output piece"
    )
    for label, block in fixture["sections"]:
        assert block in recovered_blocks, (
            "label %r's block must survive apply_format byte-identical; got pieces %r"
            % (label, recovered)
        )


def test_field_order_label_with_no_matching_section_is_omitted():
    # The OMIT half of data-model.md §8: pair entries-labeled-causal.json's `sections`
    # against entries-consistent.json's resolved structure. That structure's
    # field_order carries "resolution" and "follow-ups", neither of which has a
    # matching block among entries-labeled-causal's sections — both must be omitted
    # entirely, never emitted as an empty heading.
    consistent_structure = resolve_format(None, _entries("entries-consistent"))["structure"]
    labeled_causal_sections = load_fixture("diary", "entries-labeled-causal.json")["sections"]

    output = apply_format(consistent_structure, labeled_causal_sections)

    assert "## Resolution" not in output
    assert "## Follow-ups" not in output
    # And the omission is not a side effect of dropping everything: the two sections
    # that DO match (What happened, Timeline) still emit, and the three unmatched
    # labeled-causal sections still get appended — no content silently vanishes.
    assert "## What happened" in output
    assert "## Timeline" in output
    assert "## Root cause (proposal)" in output
    assert "## Contributing factors (proposals)" in output
    assert "## Action items (proposals)" in output


# ---------------------------------------------------------------------------
# Bounded extraction — a large filler block with no heading, no line-initial
# Label:, and no date costs the extracted Structure nothing.
# ---------------------------------------------------------------------------


def test_extraction_is_bounded_by_a_large_content_free_filler_block():
    entries = _entries("entries-consistent")
    golden = GOLDEN["entries-consistent"][0]

    # No "#"/"**" heading line, no line-initial "Label:" field, and no date anywhere —
    # every sentence starts mid-word-safe lowercase prose with no colon and no digit.
    filler_sentence = (
        "this filler line carries no heading marker no inline label and no date "
    )
    filler = "\n".join([filler_sentence] * 5000)
    assert ":" not in filler and not any(character.isdigit() for character in filler)

    extended_content = entries[0]["content"] + "\n" + filler
    assert extract_structure(extended_content) == golden, (
        "a large, structure-free filler block must never change the extracted "
        "Structure — extraction reads only for title/headings/date/field_order "
        "(data-model.md 'Extraction is bounded')"
    )


# ---------------------------------------------------------------------------
# FR-003 input-signature property — format resolution's declared input
# vocabulary is disjoint from the session row's field names. Parsed
# DYNAMICALLY out of skills/session-store/references/schema.md's column
# table, never a test-local copy, per data-model.md §9's own instructions.
#
# Accepted-weak gate (data-model.md §9): the two vocabularies are disjoint
# by ordinary English, not by construction, so no plausible edit makes this
# fire. Its real value is the non-vacuity half below — proving the row-field
# parser actually works and the declared input set matches the prose.
# ---------------------------------------------------------------------------

_ROW_FIELD_RE = re.compile(r"^\| `([a-zA-Z_]+)` \|", re.MULTILINE)


def _parse_row_field_names():
    schema_path = REPO_ROOT / "skills" / "session-store" / "references" / "schema.md"
    text = schema_path.read_text(encoding="utf-8")
    start = text.index("## Column table")
    end = text.index("\n## ", start + 1)
    return frozenset(_ROW_FIELD_RE.findall(text[start:end]))


ROW_FIELD_NAMES = _parse_row_field_names()


def test_row_field_names_parsed_from_schema_are_non_vacuous():
    # The load-bearing half of this accepted-weak gate: prove the dynamic parser found
    # something real, not an empty set that would make the disjointness check below
    # vacuously true.
    assert ROW_FIELD_NAMES, "the schema.md column-table parser must find at least one field"
    assert "diary_url" in ROW_FIELD_NAMES, (
        "the parser must find diary_url specifically — its absence would mean the "
        "parser is reading the wrong table or the wrong file"
    )


def test_format_input_keys_disjoint_from_session_row_field_names():
    assert FORMAT_INPUT_KEYS.isdisjoint(ROW_FIELD_NAMES), (
        "FORMAT_INPUT_KEYS must share no name with a session-row column (data-model.md "
        "§9's FR-003 instrument)"
    )


def test_resolve_format_signature_disjoint_from_session_row_field_names():
    signature_params = set(inspect.signature(resolve_format).parameters)
    assert signature_params.isdisjoint(ROW_FIELD_NAMES), (
        "resolve_format's own parameter names must share no name with a session-row "
        "column either — the signature is the second half of the FR-003 instrument"
    )
