"""T011 / US1 / SC-002 / SC-003: diary format resolution and structure extraction
behave exactly as documented, with zero silent picks on numeric-date ambiguity.

Ties ``tests/helpers/diary_reference.py``'s ``extract_structure`` /
``resolve_date_ambiguity`` / ``resolve_format`` / ``apply_format`` (T006/T007/T009) to
``tests/fixtures/diary/golden-structures.json`` and
``tests/fixtures/diary/resolution-matrix.json`` (T010) and to
``skills/diary/references/format.md`` (data-model.md §3, §3.1, §4, §5, §6, §8, §9).

Everything here is parametrized off the two fixtures — no hand-written expected
``Structure``/notice/source values live in this module. Both fixtures were generated by
running the reference encoding and then hand-audited against data-model.md (T010's own
job); this module only re-asserts on the artifacts, never on prose (Constitution VIII).

House style follows ``tests/contract/test_catalog_resolution.py``: a non-vanishing guard
on each fixture's case-id/key set first, then full parametrization over every case.
"""

import datetime
import inspect
import re

import pytest

from conftest import REPO_ROOT, fixture_path, load_fixture
from helpers.diary_reference import (
    FORMAT_INPUT_KEYS,
    MINIMAL_DEFAULT,
    _date_format_for_line,
    apply_format,
    extract_structure,
    render_date,
    resolve_date_ambiguity,
    resolve_format,
)

MATRIX = load_fixture("diary", "resolution-matrix.json")
CASES = MATRIX["cases"]
CASES_BY_ID = {case["id"]: case for case in CASES}

GOLDEN = load_fixture("diary", "golden-structures.json")


def _entries(fixture_name):
    return load_fixture("diary", "{}.json".format(fixture_name))["entries"]


# ---------------------------------------------------------------------------
# Non-vanishing guards, first (test_catalog_resolution.py's TA5-style
# precedent) — a truncated or renamed fixture must fail here, not silently
# shrink a parametrize below to a smaller, still-green set.
# ---------------------------------------------------------------------------

EXPECTED_CASE_IDS = frozenset(
    {
        "template-absent-entries-consistent",
        "template-absent-entries-bold",
        "template-absent-entries-inconsistent",
        "template-absent-entries-ambiguous-date",
        "template-absent-entries-disambiguating",
        "template-absent-entries-short",
        "template-absent-entries-empty",
        "template-well-formed",
        "template-malformed-number",
        "template-malformed-object",
        "template-malformed-empty-string",
        "template-malformed-whitespace-only",
        "template-malformed-empty",
    }
)

EXPECTED_GOLDEN_KEYS = frozenset(
    {
        "entries-consistent",
        "entries-bold",
        "entries-inconsistent",
        "entries-ambiguous-date",
        "entries-disambiguating",
        "entries-short",
        "entries-labeled-causal",
        "MINIMAL_DEFAULT",
    }
)


def test_matrix_case_ids_are_exactly_the_documented_set():
    case_ids = set(CASES_BY_ID)
    assert case_ids == EXPECTED_CASE_IDS, (
        "resolution-matrix.json's case-id set must equal the documented set exactly — "
        "a renamed or dropped id must fail here rather than silently disappearing from "
        "the parametrize below; missing=%r extra=%r"
        % (sorted(EXPECTED_CASE_IDS - case_ids), sorted(case_ids - EXPECTED_CASE_IDS))
    )


def test_golden_structures_cover_every_entry_fixture_set_and_the_default():
    assert set(GOLDEN) == EXPECTED_GOLDEN_KEYS, (
        "golden-structures.json must carry exactly one list per entries-*.json fixture "
        "plus MINIMAL_DEFAULT; missing=%r extra=%r"
        % (
            sorted(EXPECTED_GOLDEN_KEYS - set(GOLDEN)),
            sorted(set(GOLDEN) - EXPECTED_GOLDEN_KEYS),
        )
    )


def test_golden_minimal_default_matches_the_encoding_constant():
    # golden-structures.json's MINIMAL_DEFAULT entry must be the same value as the
    # module's own hand-written constant (data-model.md §6), not merely a plausible
    # look-alike copied in by hand — this is what makes it safe to reuse below instead
    # of a fixture-local re-typing of the same seven sections.
    assert GOLDEN["MINIMAL_DEFAULT"] == MINIMAL_DEFAULT


# ---------------------------------------------------------------------------
# The resolution matrix (SC-002) — source, the exact notice SET, and the
# resolved structure, per case.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("case", CASES, ids=[case["id"] for case in CASES])
def test_matrix_case_resolves_exactly_as_expected(case):
    entries = _entries(case["entries_fixture"])
    resolution = resolve_format(case["template"], entries)
    expected = case["expected"]

    assert resolution["source"] == expected["source"], (
        "%s: source must be %r — %s; got %r"
        % (case["id"], expected["source"], case["why"], resolution["source"])
    )
    # Notices compared as a SET and exactly — never "contains" — so a spurious extra
    # notice (or a missing one) fails here.
    actual_notice_kinds = set(notice["kind"] for notice in resolution["notices"])
    assert actual_notice_kinds == set(expected["notices"]), (
        "%s: notice kind set must equal %r exactly — %s; got %r"
        % (case["id"], sorted(expected["notices"]), case["why"], sorted(actual_notice_kinds))
    )
    assert resolution["structure"] == expected["resolved"], (
        "%s: resolved structure must equal the fixture's expectation field-for-field — "
        "%s" % (case["id"], case["why"])
    )


# ---------------------------------------------------------------------------
# Extraction goldens (SC-003) — per entry, field-for-field.
# ---------------------------------------------------------------------------

_GOLDEN_ENTRY_CASES = []
for _fixture_name, _structures in GOLDEN.items():
    if _fixture_name == "MINIMAL_DEFAULT":
        continue
    _entries_list = _entries(_fixture_name)
    assert len(_entries_list) == len(_structures), (
        "%s: golden-structures.json must carry exactly one Structure per entry"
        % _fixture_name
    )
    for _index, (_entry, _expected) in enumerate(zip(_entries_list, _structures)):
        _GOLDEN_ENTRY_CASES.append((_fixture_name, _index, _entry["content"], _expected))

_GOLDEN_ENTRY_IDS = ["{}[{}]".format(name, index) for name, index, _, _ in _GOLDEN_ENTRY_CASES]


@pytest.mark.parametrize(
    "fixture_name, index, content, expected", _GOLDEN_ENTRY_CASES, ids=_GOLDEN_ENTRY_IDS
)
def test_extraction_golden_matches_field_for_field(fixture_name, index, content, expected):
    assert extract_structure(content) == expected, (
        "%s entry %d: extract_structure(content) must equal the golden Structure "
        "field-for-field (SC-003)" % (fixture_name, index)
    )


# ---------------------------------------------------------------------------
# The template branch's no-read property (US1 AS-1) — a real trap, not a
# plain list, so any consumption at all (iteration, len, truth-test,
# indexing) fails loudly rather than silently.
# ---------------------------------------------------------------------------


class _RaisingEntries:
    """Stands in for ``entries`` on the template-configured path. Every way a
    caller might read it — iterate, measure, truth-test, index — raises, so
    a ``resolve_format`` that touches ``entries`` at all on this path fails
    the test instead of merely "happening" to work because a real list was
    never actually consumed."""

    def __iter__(self):
        raise AssertionError("entries must not be iterated when a template is configured")

    def __len__(self):
        raise AssertionError("entries must not be measured when a template is configured")

    def __bool__(self):
        raise AssertionError("entries must not be truth-tested when a template is configured")

    def __getitem__(self, item):
        raise AssertionError("entries must not be indexed when a template is configured")


def test_template_branch_never_reads_entries():
    resolution = resolve_format("a well-formed configured template", _RaisingEntries())
    assert resolution == {
        "source": "template",
        "structure": None,
        "template": "a well-formed configured template",
        "notices": [],
    }


# ---------------------------------------------------------------------------
# Freshest-wins on entries-inconsistent.json — both the resulting structure
# and the entries_inconsistent notice.
# ---------------------------------------------------------------------------


def test_freshest_wins_structure_and_notice_on_inconsistent_entries():
    entries = _entries("entries-inconsistent")
    resolution = resolve_format(None, entries)

    assert set(notice["kind"] for notice in resolution["notices"]) == {"entries_inconsistent"}
    # The newest entry (index 0 — read_recent is most-recent-first) is what freshest-wins
    # adopts; golden-structures.json's own per-entry extraction of that same entry is the
    # independent source for what that structure must be, so this is not a second
    # hand-written copy of the same expectation.
    assert resolution["structure"] == GOLDEN["entries-inconsistent"][0]
    assert resolution["structure"] == CASES_BY_ID["template-absent-entries-inconsistent"][
        "expected"
    ]["resolved"]


# ---------------------------------------------------------------------------
# date_ambiguous on entries-ambiguous-date.json; its ABSENCE on
# entries-disambiguating.json, plus the resolved order propagated to every
# entry of the pass (resolve_format only ever returns entries[0]'s
# structure, so the propagation claim needs resolve_date_ambiguity called
# directly over the whole pass to be observable at all).
# ---------------------------------------------------------------------------


def test_date_ambiguous_notice_on_every_component_ambiguous_entries():
    resolution = resolve_format(None, _entries("entries-ambiguous-date"))
    assert set(notice["kind"] for notice in resolution["notices"]) == {"date_ambiguous"}


def test_disambiguating_entries_carry_no_date_ambiguous_notice():
    resolution = resolve_format(None, _entries("entries-disambiguating"))
    assert "date_ambiguous" not in set(notice["kind"] for notice in resolution["notices"])


def test_disambiguating_resolved_order_propagates_to_every_entry_in_the_pass():
    # The single unambiguous entry (third-newest, data-model.md §3.1 step 2) fixes the
    # order for the WHOLE pass, not just the newest entry resolve_format happens to
    # return. The expected pattern comes from the matrix fixture's own recorded
    # resolution, not a value typed into this test.
    expected_date_format = CASES_BY_ID["template-absent-entries-disambiguating"]["expected"][
        "resolved"
    ]["date_format"]

    entries = _entries("entries-disambiguating")
    structures = [extract_structure(entry["content"]) for entry in entries]
    resolved = resolve_date_ambiguity(structures)

    assert len(resolved) == len(entries)
    for structure in resolved:
        assert structure["date_format"] == expected_date_format, (
            "every entry in the pass must carry the adopted order, not only the "
            "entry resolve_format happens to return"
        )


# ---------------------------------------------------------------------------
# Malformed-template rows — the fallback structure is the match-recent one,
# never the default.
# ---------------------------------------------------------------------------

_MALFORMED_CASE_IDS = [
    case_id for case_id in CASES_BY_ID if case_id.startswith("template-malformed-")
]


def test_matrix_carries_more_than_one_malformed_shape():
    # "not a string" has more than one JSON shape (a number, an object) — this guards
    # against the malformed rows collapsing onto a single accidentally-easy case.
    assert len(_MALFORMED_CASE_IDS) >= 4


@pytest.mark.parametrize("case_id", _MALFORMED_CASE_IDS)
def test_malformed_template_falls_back_to_match_recent_not_default(case_id):
    case = CASES_BY_ID[case_id]
    entries = _entries(case["entries_fixture"])
    resolution = resolve_format(case["template"], entries)

    assert "template_malformed" in set(notice["kind"] for notice in resolution["notices"])
    assert resolution["structure"] == case["expected"]["resolved"]

    # F10 (review round): "never silently resolve to the empty-diary
    # default" is rule 2's promise only when there is something to MATCH
    # against. format.md rule 2 says a malformed template "proceeds
    # exactly as if no template were configured" — with an EMPTY diary,
    # that is rule 4's minimal default by design, not a violation of rule
    # 2. Every malformed-* row but "template-malformed-empty" pairs with
    # entries-consistent (non-empty), so this scoping only ever bites on
    # that one row.
    if entries:
        assert resolution["source"] == "matched"
        assert resolution["structure"] != MINIMAL_DEFAULT, (
            "%s: a malformed template must fall through to match-recent, "
            "never silently resolve to the empty-diary default" % case_id
        )
    else:
        assert resolution["source"] == "default"
        assert resolution["structure"] == MINIMAL_DEFAULT
        assert "template_candidate" in set(notice["kind"] for notice in resolution["notices"])


# ---------------------------------------------------------------------------
# The minimal default plus template_candidate on entries-empty.json.
# ---------------------------------------------------------------------------


def test_empty_entries_resolves_to_the_minimal_default_constant():
    resolution = resolve_format(None, _entries("entries-empty"))
    assert resolution["source"] == "default"
    assert resolution["structure"] == MINIMAL_DEFAULT
    assert set(notice["kind"] for notice in resolution["notices"]) == {"template_candidate"}


# ---------------------------------------------------------------------------
# Label pass-through (FR-005) — every block of entries-labeled-causal.json's
# sections is byte-identical in apply_format's output, plus the
# no-content-dropped property for its unmatched-label ("Timeline") block.
# ---------------------------------------------------------------------------


def _recovered_blocks(output):
    """Splits apply_format's output back into (heading_line, block) pairs.

    apply_format emits each piece as ``heading_line + "\\n" + block + "\\n\\n"``
    (data-model.md §8); none of the blocks in entries-labeled-causal.json's own
    `sections` list contain a blank line, so splitting the joined output on "\\n\\n"
    recovers each piece verbatim and a plain `==` comparison — never a substring `in`
    check a mutated block could still pass — is enough to prove byte-identity.
    """
    pieces = [piece for piece in output.split("\n\n") if piece]
    return [piece.split("\n", 1) for piece in pieces]


def test_label_pass_through_is_byte_identical_for_every_block():
    fixture = load_fixture("diary", "entries-labeled-causal.json")
    structure = resolve_format(None, fixture["entries"])["structure"]
    output = apply_format(structure, fixture["sections"])

    recovered = _recovered_blocks(output)
    recovered_blocks = [block for _heading, block in recovered]

    assert len(recovered) == len(fixture["sections"]), (
        "no content is ever dropped (data-model.md §8) — every input section must "
        "produce exactly one output piece"
    )
    for label, block in fixture["sections"]:
        assert block in recovered_blocks, (
            "label %r's block must survive apply_format byte-identical; got pieces %r"
            % (label, recovered)
        )

    # F3 (review round): the two checks above recover (heading, block) pairs
    # and then DISCARD the headings, asserting only "this block is present
    # somewhere" — a regression that emitted, say, the action-items block
    # under the "Root cause (proposal)" heading would still pass both of
    # them (same set of blocks, same count), which is exactly Constitution
    # V's failure mode: a causal proposal silently relabeled. Assert the
    # full recovered (heading_text, block) SEQUENCE against the expected
    # pairing instead — every one of this fixture's labels has a matching
    # heading with the SAME text (data-model.md §8's field_order-matched
    # emission), so the expected heading for each block is "## " + its own
    # input label, in the fixture's own field_order-then-append order.
    # Normalization mirrors data-model.md §3/§8's documented rule (lowercase,
    # trailing ':' stripped, whitespace collapsed) — none of this fixture's
    # labels need more than lowercasing, but the rule is restated here in
    # full rather than relied on by coincidence.
    def _normalize(text):
        text = text.strip()
        if text.endswith(":"):
            text = text[:-1].strip()
        return re.sub(r"\s+", " ", text).lower()

    blocks_by_original_label = dict(fixture["sections"])
    normalized_to_original = {
        _normalize(label): label for label, _block in fixture["sections"]
    }
    resolved_field_order = structure["field_order"]
    ordered_normalized_labels = [
        normalized for normalized in resolved_field_order if normalized in normalized_to_original
    ] + [
        _normalize(label)
        for label, _block in fixture["sections"]
        if _normalize(label) not in resolved_field_order
    ]
    expected_pairs = [
        [
            "## " + normalized_to_original[normalized],
            blocks_by_original_label[normalized_to_original[normalized]],
        ]
        for normalized in ordered_normalized_labels
    ]
    assert recovered == expected_pairs, (
        "apply_format must place each block under ITS OWN label's heading, "
        "in field_order-then-append order — got %r, expected %r"
        % (recovered, expected_pairs)
    )


def test_field_order_label_with_no_matching_section_is_omitted():
    # The OMIT half of data-model.md §8: pair entries-labeled-causal.json's `sections`
    # against entries-consistent.json's resolved structure. That structure's
    # field_order carries "resolution" and "follow-ups", neither of which has a
    # matching block among entries-labeled-causal's sections — both must be omitted
    # entirely, never emitted as an empty heading.
    consistent_structure = resolve_format(None, _entries("entries-consistent"))["structure"]
    labeled_causal_sections = load_fixture("diary", "entries-labeled-causal.json")["sections"]

    output = apply_format(consistent_structure, labeled_causal_sections)

    assert "## Resolution" not in output
    assert "## Follow-ups" not in output
    # And the omission is not a side effect of dropping everything: the two sections
    # that DO match (What happened, Timeline) still emit, and the three unmatched
    # labeled-causal sections still get appended — no content silently vanishes.
    assert "## What happened" in output
    assert "## Timeline" in output
    assert "## Root cause (proposal)" in output
    assert "## Contributing factors (proposals)" in output
    assert "## Action items (proposals)" in output


def test_apply_format_does_not_raise_when_a_matched_heading_omits_level():
    # F8 (review round): apply_format used to index heading["marker"] /
    # heading["level"] directly, while every sibling read in this module
    # (_modal_marker_level, extract_structure) already tolerates a missing
    # key via `.get`. A structure whose heading dict omits "level" (a
    # hand-built Structure, e.g. one a caller assembles rather than one
    # extract_structure produced) raised KeyError here.
    structure = {
        "title": None,
        "sections": [{"marker": "atx", "text": "What happened"}],  # no "level"
        "date_format": None,
        "field_order": ["what happened"],
    }
    output = apply_format(structure, [["What happened", "Body text."]])
    assert "What happened" in output
    assert "Body text." in output


# ---------------------------------------------------------------------------
# Bounded extraction — a large filler block with no heading, no line-initial
# Label:, and no date costs the extracted Structure nothing.
# ---------------------------------------------------------------------------


def test_extraction_is_bounded_by_a_large_content_free_filler_block():
    entries = _entries("entries-consistent")
    golden = GOLDEN["entries-consistent"][0]

    # No "#"/"**" heading line, no line-initial "Label:" field, and no date anywhere —
    # every sentence starts mid-word-safe lowercase prose with no colon and no digit.
    filler_sentence = (
        "this filler line carries no heading marker no inline label and no date "
    )
    filler = "\n".join([filler_sentence] * 5000)
    assert ":" not in filler and not any(character.isdigit() for character in filler)

    extended_content = entries[0]["content"] + "\n" + filler
    assert extract_structure(extended_content) == golden, (
        "a large, structure-free filler block must never change the extracted "
        "Structure — extraction reads only for title/headings/date/field_order "
        "(data-model.md 'Extraction is bounded')"
    )


# ---------------------------------------------------------------------------
# render_date (data-model.md §8) — F1 (BLOCKING): every documented worked
# pattern must round-trip byte-for-byte. Before the fix, `_DATE_TOKEN_RE`'s
# alternation was first-match-wins (not longest-match-wins), so "M" matched
# before "Month"/"Mon" ever got a chance — every named-month pattern came
# back corrupted (e.g. "DD Mon YYYY" rendered "21 7on 2026").
# ---------------------------------------------------------------------------

_RENDER_DATE_WORKED_CASES = (
    ("YYYY-MM-DD", datetime.date(2026, 7, 21), "2026-07-21"),
    ("DD Mon YYYY", datetime.date(2026, 7, 21), "21 Jul 2026"),
    ("Month D, YYYY", datetime.date(2026, 7, 4), "July 4, 2026"),
    ("MM/DD/YYYY", datetime.date(2026, 7, 21), "07/21/2026"),
)


@pytest.mark.parametrize(
    "pattern, when, expected",
    _RENDER_DATE_WORKED_CASES,
    ids=[case[0] for case in _RENDER_DATE_WORKED_CASES],
)
def test_render_date_round_trips_every_documented_worked_pattern(pattern, when, expected):
    # These are the exact four worked cases data-model.md §3 and
    # references/format.md's "Date-format tokens" table both cite.
    assert render_date({"pattern": pattern, "ambiguous": False}, when) == expected


# F2 — render_date / _coerce_date had zero test coverage before F1's fix
# landed (which is why F1 shipped unnoticed). Covers _coerce_date's three
# documented accepted input shapes — an object exposing .year/.month/.day,
# a (year, month, day) sequence, and an ISO "YYYY-MM-DD" string — through
# render_date, its only caller.
_COERCE_DATE_INPUT_SHAPES = (
    ("datetime.date", datetime.date(2026, 7, 21)),
    ("3-tuple", (2026, 7, 21)),
    ("3-element list", [2026, 7, 21]),
    ("iso string", "2026-07-21"),
)


@pytest.mark.parametrize(
    "shape_name, value",
    _COERCE_DATE_INPUT_SHAPES,
    ids=[case[0] for case in _COERCE_DATE_INPUT_SHAPES],
)
def test_render_date_accepts_every_documented_coerce_date_input_shape(shape_name, value):
    assert render_date({"pattern": "YYYY-MM-DD", "ambiguous": False}, value) == "2026-07-21"


# ---------------------------------------------------------------------------
# F4 — the documented YY (2-digit year) token, fixture-free. Before this
# fix, a title like "# 07/21/26 — checkout: latency" carried no
# date-bearing line at all (the year-last numeric regex required 4 written
# digits), so the title fell into `sections`/`field_order` instead of
# `title` — and because a real title varies per entry, an otherwise
# perfectly uniform diary would classify as entries_inconsistent forever.
# ---------------------------------------------------------------------------


def test_two_digit_year_title_is_recognized_and_uniform_entries_are_not_inconsistent():
    entries = [
        {
            "link": "diary-yy-newest",
            "content": (
                "# 07/22/26 — checkout: brief latency\n\n"
                "## What happened\nBody text.\n\n"
                "## Timeline\nBody text.\n\n"
                "## Resolution\nBody text.\n"
            ),
            "at": "2026-07-22T00:00:00Z",
        },
        {
            "link": "diary-yy-oldest",
            "content": (
                "# 07/21/26 — checkout: latency\n\n"
                "## What happened\nBody text.\n\n"
                "## Timeline\nBody text.\n\n"
                "## Resolution\nBody text.\n"
            ),
            "at": "2026-07-21T00:00:00Z",
        },
    ]

    for entry in entries:
        structure = extract_structure(entry["content"])
        assert structure["title"] is not None, (
            "a 2-digit-year title line must be recognized as date-bearing, not fall "
            "through into `sections`"
        )
        assert structure["date_format"] == {"pattern": "MM/DD/YY", "ambiguous": False}

    resolution = resolve_format(None, entries)
    assert resolution["source"] == "matched"
    assert "entries_inconsistent" not in set(
        notice["kind"] for notice in resolution["notices"]
    ), "uniform entries sharing one section/date shape must never classify as inconsistent"


# ---------------------------------------------------------------------------
# F5 — resolve_date_ambiguity must not let read order silently pick a
# winner when the pass carries CONFLICTING unambiguous entries (one
# clearly day-first, another clearly month-first). Before this fix, a
# `break` on the first unambiguous entry encountered adopted its order for
# every ambiguous entry in the pass, clearing every `ambiguous` flag with
# no notice — exactly the silent pick data-model.md §3.1 forbids.
# ---------------------------------------------------------------------------


def test_resolve_date_ambiguity_declines_to_pick_when_the_pass_conflicts():
    day_first = {
        "title": None, "sections": [], "field_order": [],
        "date_format": {"pattern": "DD/MM/YYYY", "ambiguous": False},
    }
    month_first = {
        "title": None, "sections": [], "field_order": [],
        "date_format": {"pattern": "MM/DD/YYYY", "ambiguous": False},
    }
    genuinely_ambiguous = {
        "title": None, "sections": [], "field_order": [],
        "date_format": {"pattern": "MM/DD/YYYY", "ambiguous": True},
    }

    structures = [day_first, month_first, genuinely_ambiguous]
    resolved = resolve_date_ambiguity(structures)

    assert resolved == structures, (
        "conflicting unambiguous entries must not let the pass adopt either order — "
        "every structure must pass through unchanged rather than have read order "
        "silently break the tie"
    )


def test_resolve_format_surfaces_date_ambiguous_when_the_pass_conflicts():
    entries = [
        {
            "link": "diary-conflict-newest",
            "content": "# 17/06/2026 — checkout: incident\n\n## What happened\nBody.\n",
            "at": "2026-06-17T00:00:00Z",
        },
        {
            "link": "diary-conflict-middle",
            "content": "# 06/17/2026 — checkout: incident\n\n## What happened\nBody.\n",
            "at": "2026-06-16T00:00:00Z",
        },
        {
            "link": "diary-conflict-oldest",
            "content": "# 03/04/2026 — checkout: incident\n\n## What happened\nBody.\n",
            "at": "2026-06-15T00:00:00Z",
        },
    ]

    resolution = resolve_format(None, entries)
    notice_kinds = set(notice["kind"] for notice in resolution["notices"])
    assert "date_ambiguous" in notice_kinds, (
        "two individually-unambiguous entries that disagree on day/month order must "
        "surface date_ambiguous rather than let read order silently pick a winner"
    )


# ---------------------------------------------------------------------------
# F6 — _flip_day_month must never raise on a pattern that isn't a
# day/month numeric shape (or is None). Before this fix, an ambiguous
# structure carrying e.g. an ISO pattern raised AttributeError
# (`.match(...)` returned None, then `.group(...)` was called on it), and a
# None pattern raised TypeError before `.match` even ran.
# ---------------------------------------------------------------------------


def test_resolve_date_ambiguity_never_raises_on_a_non_matching_ambiguous_pattern():
    day_first = {
        "title": None, "sections": [], "field_order": [],
        "date_format": {"pattern": "DD/MM/YYYY", "ambiguous": False},
    }
    iso_shaped_but_flagged_ambiguous = {
        "title": None, "sections": [], "field_order": [],
        "date_format": {"pattern": "YYYY-MM-DD", "ambiguous": True},
    }
    none_pattern_but_flagged_ambiguous = {
        "title": None, "sections": [], "field_order": [],
        "date_format": {"pattern": None, "ambiguous": True},
    }

    # Must not raise (AttributeError / TypeError pre-fix).
    resolved = resolve_date_ambiguity(
        [day_first, iso_shaped_but_flagged_ambiguous, none_pattern_but_flagged_ambiguous]
    )

    # The guard's own contract: a non-matching pattern is returned UNCHANGED
    # rather than crashing or being silently rewritten into something else.
    assert resolved[1]["date_format"]["pattern"] == "YYYY-MM-DD"
    assert resolved[2]["date_format"]["pattern"] is None


# ---------------------------------------------------------------------------
# G7 (round 2) — F6's own guard, `pattern or ""`, only rescues FALSY inputs
# (None, ""). A non-string, TRUTHY pattern (e.g. an int) is untouched by
# `or ""` and reaches `.match(...)` anyway, raising TypeError — the exact
# thing F6's docstring claims never happens ("returned UNCHANGED rather
# than raising"). The fixed guard checks the type directly.
# ---------------------------------------------------------------------------


def test_flip_day_month_returns_a_non_string_pattern_unchanged_rather_than_raising():
    from helpers.diary_reference import _flip_day_month

    # Must not raise (TypeError pre-fix, since `42 or ""` is truthy `42`,
    # and `_PATTERN_DAYMONTH_RE.match(42)` raises on a non-string subject).
    assert _flip_day_month(42) == 42
    # The two FALSY inputs F6 already covered must still behave the same
    # way post-fix — this guards against the isinstance rewrite narrowing
    # coverage rather than only widening it.
    assert _flip_day_month(None) is None
    assert _flip_day_month("") == ""


# ---------------------------------------------------------------------------
# F12 — a numeric run glued to more digits/dots on either side must not be
# read as a date component; it is far more likely a fragment of something
# else (a version string, a build number). Calendar validity is
# deliberately NOT part of this: a genuinely standalone "1234-56-78" still
# reads as YYYY-MM-DD (data-model.md §3's own "we extract a format, not a
# valid date" posture).
# ---------------------------------------------------------------------------


def test_date_shape_false_positive_on_a_version_string_is_rejected():
    assert _date_format_for_line("Version 1.2.3-4/5/2026") is None


def test_standalone_iso_shaped_digits_still_read_as_a_format_with_no_calendar_check():
    # Deliberately NOT a valid calendar date — extraction reads a format,
    # never validates a value (data-model.md §3).
    assert _date_format_for_line("1234-56-78") == {"pattern": "YYYY-MM-DD", "ambiguous": False}


# ---------------------------------------------------------------------------
# G1 (REGRESSION, round 2) — F12's trailing guard, `(?![\d.])`, blocked a
# bare "." right after a date, not just a "." glued to more digits. A
# sentence-final date ("See 07/21/2026.") — or an entry titled with one
# ("# Outage on 07/21/2026.") — carried no date-bearing line at all,
# which is a REGRESSION relative to pre-round-1 behavior: these parsed
# before F12 landed. The fix narrows the guard to reject only what F12
# actually needs rejected (a bare digit right after, or a "." immediately
# followed by a digit), while a "." followed by nothing or a non-digit now
# passes.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "line",
    [
        "See 07/21/2026.",
        "July 4, 2026.",
        "2026-07-21.",
    ],
)
def test_sentence_final_dates_now_parse(line):
    assert _date_format_for_line(line) is not None, (
        "%r must carry a recognized date-bearing line — a trailing '.' "
        "with nothing after it is not a version-string/build-number glue "
        "character, and must not block recognition (G1 regression)" % line
    )


@pytest.mark.parametrize(
    "line",
    [
        "Version 1.2.3-4/5/2026",
        "07/21/2026.5",
        "build 2026-07-21-3",
    ],
)
def test_digit_glued_dates_still_rejected_after_the_g1_fix(line):
    # The G1 fix must not reopen F12's own hole: a numeric run still glued
    # to more digits/dots on either side (a version string, a trailing
    # ".5", a trailing "-3") must still read as no date at all.
    assert _date_format_for_line(line) is None, (
        "%r must still carry no recognized date — the G1 fix narrows the "
        "trailing guard, it must not remove F12's own protection" % line
    )


def test_entry_title_with_a_sentence_final_date_is_recognized_as_date_bearing():
    # The downstream consequence G1 names: a title ending in a bare "."
    # right after its date must still be treated as the entry's title (and
    # excluded from the compared shape), not fall into `sections` the way
    # an unrecognized-date title would (format.md "When the title line's
    # date isn't recognized").
    content = (
        "# Outage on 07/21/2026.\n\n"
        "## What happened\nBody text.\n\n"
        "## Timeline\nBody text.\n"
    )
    structure = extract_structure(content)
    assert structure["title"] is not None
    assert structure["title"]["text"] == "Outage on 07/21/2026."
    assert structure["date_format"] == {"pattern": "MM/DD/YYYY", "ambiguous": False}
    # And the title heading itself must not leak into sections/field_order.
    assert all(heading["text"] != structure["title"]["text"] for heading in structure["sections"])


# ---------------------------------------------------------------------------
# G2 (round 2) — F4 widened 2-digit-year support to the year-last numeric
# shape only, so the named-month shapes still required 4 written digits: a
# title like "# 21 Jul 26 — payments: outage" or "July 4, 26" carried no
# date-bearing line at all — the exact F4 failure mode, reached through a
# different shape. Fixture-free, same style as F4's own test.
# ---------------------------------------------------------------------------


def test_two_digit_year_is_recognized_in_the_day_monthname_year_shape():
    assert _date_format_for_line("21 Jul 26") == {"pattern": "DD Mon YY", "ambiguous": False}


def test_two_digit_year_is_recognized_in_the_monthname_day_year_shape():
    assert _date_format_for_line("July 4, 26") == {"pattern": "Month D, YY", "ambiguous": False}


def test_two_digit_year_named_month_titles_are_recognized_and_uniform_entries_are_not_inconsistent():
    entries = [
        {
            "link": "diary-named-month-yy-newest",
            "content": (
                "# 22 Jul 26 — checkout: brief latency\n\n"
                "## What happened\nBody text.\n\n"
                "## Timeline\nBody text.\n\n"
                "## Resolution\nBody text.\n"
            ),
            "at": "2026-07-22T00:00:00Z",
        },
        {
            "link": "diary-named-month-yy-oldest",
            "content": (
                "# 21 Jul 26 — checkout: latency\n\n"
                "## What happened\nBody text.\n\n"
                "## Timeline\nBody text.\n\n"
                "## Resolution\nBody text.\n"
            ),
            "at": "2026-07-21T00:00:00Z",
        },
    ]

    for entry in entries:
        structure = extract_structure(entry["content"])
        assert structure["title"] is not None, (
            "a 2-digit-year named-month title line must be recognized as "
            "date-bearing, not fall through into `sections`"
        )
        assert structure["date_format"] == {"pattern": "DD Mon YY", "ambiguous": False}

    resolution = resolve_format(None, entries)
    assert resolution["source"] == "matched"
    assert "entries_inconsistent" not in set(
        notice["kind"] for notice in resolution["notices"]
    ), "uniform entries sharing one section/date shape must never classify as inconsistent"


# ---------------------------------------------------------------------------
# H1 (round 3, REGRESSION fix) — G2's unconditional 2-digit-year widening
# for the two named-month shapes made ordinary English prose read as a
# date: "On Jul 4, 15 nodes went down." (Mon D, YY), "Rolled back 3 Jul 15
# minutes later." (D Mon YY), and "Dec 25, 10 alerts fired." (Mon DD, YY)
# all returned None before G2 landed, and a fabricated date_format from a
# body line like this can trip a spurious entries_inconsistent end to end.
# The fix gates the 2-digit alternative on trailing context (end-of-line or
# one of "— – : , ) ]", surrounding whitespace allowed); the 4-digit
# alternative, and the year-last numeric shape, are untouched.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "line",
    [
        "On Jul 4, 15 nodes went down.",
        "Rolled back 3 Jul 15 minutes later.",
        "Dec 25, 10 alerts fired.",
    ],
)
def test_named_month_two_digit_year_prose_is_not_read_as_a_date(line):
    assert _date_format_for_line(line) is None, (
        "%r is ordinary prose, not a date — a 2-digit year with no "
        "title-ish trailing context must not fabricate a date_format "
        "(H1 regression)" % line
    )


@pytest.mark.parametrize(
    "line, expected_pattern",
    [
        ("# 21 Jul 26 — payments: outage", "DD Mon YY"),
        ("July 4, 26", "Month D, YY"),
    ],
)
def test_named_month_two_digit_year_still_parses_with_title_ish_trailing_context(
    line, expected_pattern
):
    # The positive half of H1's fix: a title line and a line-final date both
    # carry trailing context the gate accepts (an em dash for the title, end
    # of line for the line-final case), so both must keep parsing.
    assert _date_format_for_line(line) == {"pattern": expected_pattern, "ambiguous": False}


# ---------------------------------------------------------------------------
# H6 (round 3) — month-name matching is case-insensitive: "3 jul 2026" and
# "JULY 4, 2026" both returned None before this fix. Canonical rendering
# ("Mon" / "July") is untouched — only recognition is case-insensitive.
# ---------------------------------------------------------------------------


def test_lowercase_month_name_is_recognized():
    assert _date_format_for_line("3 jul 2026") == {"pattern": "D Mon YYYY", "ambiguous": False}


def test_uppercase_month_name_is_recognized():
    assert _date_format_for_line("JULY 4, 2026") == {
        "pattern": "Month D, YYYY",
        "ambiguous": False,
    }


@pytest.mark.parametrize(
    "line",
    [
        "on jul 4, 15 nodes went down.",
        "rolled back 3 jul 15 minutes later.",
        "dec 25, 10 alerts fired.",
    ],
)
def test_lowercased_prose_false_positives_still_rejected_after_case_insensitive_months(line):
    # H6 must not reopen H1: lowercasing the same three prose lines that H1
    # pins as rejections must still return None once month names match
    # case-insensitively.
    assert _date_format_for_line(line) is None, (
        "%r must still be rejected — case-insensitive month matching (H6) "
        "must not widen H1's prose false-positive gate" % line
    )


# ---------------------------------------------------------------------------
# FR-003 input-signature property — format resolution's declared input
# vocabulary is disjoint from the session row's field names. Parsed
# DYNAMICALLY out of skills/session-store/references/schema.md's column
# table, never a test-local copy, per data-model.md §9's own instructions.
#
# Accepted-weak gate (data-model.md §9): the two vocabularies are disjoint
# by ordinary English, not by construction, so no plausible edit makes this
# fire. Its real value is the non-vacuity half below — proving the row-field
# parser actually works and the declared input set matches the prose.
# ---------------------------------------------------------------------------

_ROW_FIELD_RE = re.compile(r"^\| `([a-zA-Z_]+)` \|", re.MULTILINE)


def _parse_row_field_names():
    schema_path = REPO_ROOT / "skills" / "session-store" / "references" / "schema.md"
    text = schema_path.read_text(encoding="utf-8")
    start = text.index("## Column table")
    end = text.index("\n## ", start + 1)
    return frozenset(_ROW_FIELD_RE.findall(text[start:end]))


ROW_FIELD_NAMES = _parse_row_field_names()


def test_row_field_names_parsed_from_schema_are_non_vacuous():
    # The load-bearing half of this accepted-weak gate: prove the dynamic parser found
    # something real, not an empty set that would make the disjointness check below
    # vacuously true.
    assert ROW_FIELD_NAMES, "the schema.md column-table parser must find at least one field"
    assert "diary_url" in ROW_FIELD_NAMES, (
        "the parser must find diary_url specifically — its absence would mean the "
        "parser is reading the wrong table or the wrong file"
    )


def test_format_input_keys_disjoint_from_session_row_field_names():
    assert FORMAT_INPUT_KEYS.isdisjoint(ROW_FIELD_NAMES), (
        "FORMAT_INPUT_KEYS must share no name with a session-row column (data-model.md "
        "§9's FR-003 instrument)"
    )


def test_resolve_format_signature_disjoint_from_session_row_field_names():
    signature_params = set(inspect.signature(resolve_format).parameters)
    assert signature_params.isdisjoint(ROW_FIELD_NAMES), (
        "resolve_format's own parameter names must share no name with a session-row "
        "column either — the signature is the second half of the FR-003 instrument"
    )
